FROM node:20-alpine
WORKDIR /app

# Cài dependencies
COPY package*.json ./
RUN npm install

# Copy code frontend
COPY . .

# Expose port Vite
EXPOSE 5173

# CMD dev: Vite server
CMD ["npm", "run", "dev", "--", "--host"]
