version: "3.9"

services:
  db:
    image: postgres:15
    container_name: my-vue-app-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: erp_base
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: my-vue-app-backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:123456@db:5432/erp_base
    ports:
      - "4000:4000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: my-vue-app-frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"

volumes:
  db-data:
