# Chọn Node 20 Alpine nhẹ
FROM node:20-alpine

# Thư mục làm việc
WORKDIR /app

# Cài build tools cho package native (pg, node-gyp...)
RUN apk add --no-cache python3 make g++

# Copy package.json + package-lock.json
COPY package*.json ./

# Cài dependencies
RUN npm install

# Copy toàn bộ source
COPY . .

# Expose port backend
EXPOSE 4000

# CMD dev: ts-node-dev watch code
CMD ["npm", "run", "dev"]
